In [104]:
import numpy as np

In [105]:
N = 10
A = np.zeros((N, N))
for i in range(N):
    for j in range(N):
        A[i, j] = N - abs(i - j)
print(A)
b = np.random.rand(N)

[[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]
 [ 9. 10.  9.  8.  7.  6.  5.  4.  3.  2.]
 [ 8.  9. 10.  9.  8.  7.  6.  5.  4.  3.]
 [ 7.  8.  9. 10.  9.  8.  7.  6.  5.  4.]
 [ 6.  7.  8.  9. 10.  9.  8.  7.  6.  5.]
 [ 5.  6.  7.  8.  9. 10.  9.  8.  7.  6.]
 [ 4.  5.  6.  7.  8.  9. 10.  9.  8.  7.]
 [ 3.  4.  5.  6.  7.  8.  9. 10.  9.  8.]
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10.  9.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]


In [106]:
# xk = np.random.rand(N)
xk = np.zeros(N)
rk = b - A @ xk
pk = rk

In [107]:
for i in range(20):
    alpha = np.dot(rk, pk) / np.dot(pk, A @ pk)
    xk1 = xk + alpha * pk
    # rk1 = b - A @ xk1
    rk1 = rk - alpha * A @ pk
    beta = -np.dot(rk1, A @ pk) / np.dot(pk, A @ pk)
    pk1 = rk1 + beta * pk
    rk = rk1
    pk = pk1
    xk = xk1
    print(np.linalg.norm(rk1))

0.608603144686226
0.5179844128625519
0.5133493980411516
0.15992177433317112
0.07925584641269648
0.01984266261076
0.002704773247863872
0.000286642856245171
0.00016431614562921774
4.403946475586563e-05
3.0941352346013586e-08
8.482971281777647e-14
1.851625162628314e-16
4.463775731957922e-16
2.85264486463587e-17
2.629937436063299e-19
1.5759426572061083e-19
4.894957013397722e-20
7.350852628039277e-21
1.4083483996340381e-22
