In [101]:
import numpy as np

In [102]:
N = 10
A = np.zeros((N, N))
for i in range(N):
    for j in range(N):
        A[i, j] = N - abs(i - j)
print(A)
b = np.random.rand(N)

[[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]
 [ 9. 10.  9.  8.  7.  6.  5.  4.  3.  2.]
 [ 8.  9. 10.  9.  8.  7.  6.  5.  4.  3.]
 [ 7.  8.  9. 10.  9.  8.  7.  6.  5.  4.]
 [ 6.  7.  8.  9. 10.  9.  8.  7.  6.  5.]
 [ 5.  6.  7.  8.  9. 10.  9.  8.  7.  6.]
 [ 4.  5.  6.  7.  8.  9. 10.  9.  8.  7.]
 [ 3.  4.  5.  6.  7.  8.  9. 10.  9.  8.]
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10.  9.]
 [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]


In [103]:
x = np.random.rand(N)
r = b - A @ x

In [104]:
for i in range(100000):
    alpha = (r @ r) / (r @ A @ r)
    x = x + alpha * r
    r = b - A @ x
    print(np.linalg.norm(r))

7.534706454080129
1.8860094595939219
1.2489219911858793
1.6009621691703175
1.0747159010192022
1.4014759108660766
0.951603655128449
1.2587614798640012
0.8624116611708137
1.1532039569266028
0.7952161300745924
1.0714608862165114
0.7420848663285398
1.0049391316636598
0.6979958426337773
0.9483257315480826
0.6598764826763226
0.8984143597912587
0.6258803098513227
0.8532860169110893
0.594900339728065
0.811784321067435
0.5662644322987495
0.7731969555552041
0.5395528375016936
0.7370684140265295
0.5144917929991466
0.7030919859385462
0.4908924179784685
0.6710480912672868
0.4686158989876949
0.6407692344363726
0.44755370880721923
0.6121200847703109
0.4276163466436725
0.5849861019835777
0.40872688609059915
0.5592669751670551
0.3908172305051047
0.5348727720011148
0.3738258936204024
0.51172161672287
0.3576966418332718
0.4897382343688926
0.34237762619943146
0.46885299004527353
0.32782079565988004
0.4490012150668142
0.3139814745310792
0.4301227030283114
0.30081803846341887
0.4121613098646544
0.2882916516